<?php

namespace mrstroz\wavecms\example\controllers;

use mrstroz\wavecms\base\grid\ActionColumn;
use mrstroz\wavecms\base\grid\PublishColumn;
use mrstroz\wavecms\base\web\Controller;
use mrstroz\wavecms\example\models\ExampleCategory;

class CategoryController extends Controller
{

    public function init()
    {
        parent::init();

        $this->view->params['h1'] = 'Categories';
        $this->query = ExampleCategory::find();

        $this->sort = true;

        $this->columns = array(
            'name',
            [
                'class' => PublishColumn::className()
            ],
            [
                'class' => ActionColumn::className(),
            ]
        );
    }

    public function actionIndex()
    {
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

}