<?php

namespace mrstroz\wavecms\example\controllers;

use mrstroz\wavecms\base\grid\ActionColumn;
use mrstroz\wavecms\base\web\Controller;
use mrstroz\wavecms\example\models\ExampleCategory;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;

class CategoryController extends Controller
{

    public function init()
    {
        parent::init();

        $this->view->params['h1'] = 'Categories';

        $this->dataProvider = new ActiveDataProvider(array(
            'query' => ExampleCategory::find()
        ));

        $this->columns = array(
            'id',
            'name',
            [
                'class' => ActionColumn::className(),
            ],
        );
    }

    public function actionIndex()
    {

        $this->view->params['buttons_top'][] = Html::a('Extra button', ['/'], ['class' => 'btn btn-default']);

        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

}