<?php

namespace mrstroz\wavecms\example\controllers;

use mrstroz\wavecms\base\grid\ActionColumn;
use mrstroz\wavecms\base\grid\PublishColumn;
use mrstroz\wavecms\base\web\Controller;
use mrstroz\wavecms\example\models\ExampleItem;
use mrstroz\wavecms\example\models\ExampleItemSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;

class ItemController extends Controller
{

    public function init()
    {
        $this->view->params['h1'] = 'Items';
        $this->query = ExampleItem::find()->joinWith(['category']);

        $this->dataProvider = new ActiveDataProvider([
            'query' => $this->query,
            'pagination' => [
                'pageSize' => 10,
            ]
        ]);

        $this->columns = array(
            'id',
            'title',
            'categoryName',
            [
                'class' => PublishColumn::className(),
            ],
            [
                'class' => ActionColumn::className(),
            ],
        );

        $this->filterModel = new ExampleItemSearch();

        parent::init();
    }

    public function actionIndex()
    {

        $this->view->params['buttons_top'][] = Html::a('Extra button', ['/'], ['class' => 'btn btn-default']);

        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

}