<?php

namespace mrstroz\wavecms\example\controllers;

use mrstroz\wavecms\base\web\Controller;
use mrstroz\wavecms\example\models\ExamplePage;

class PageController extends Controller
{

    public function init()
    {
        parent::init();

        $this->view->params['h1'] = 'Page type';
        $this->query = ExamplePage::find();
    }

    public function actionIndex()
    {
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

}